FROM node:18

# expose frontend port
EXPOSE 8080

# create necessary work directory
RUN mkdir -p /frontend/public /frontend/src
WORKDIR /frontend 

# copy local files to container
COPY package.json /frontend/package.json
COPY package-lock.json /frontend/package-lock.json


# install packages
RUN npm install 

# Download chromium for Puppeteer browser tests
# RUN npm install playwright
# RUN npx playwright install chrome
CMD ["npm", "run", "dev"]
