FROM node:18

# create necessary work directory
RUN mkdir -p /testing
WORKDIR /testing

# copy local files to container
COPY package.json /testing/package.json
COPY package-lock.json /testing/package-lock.json


# install packages
RUN npm install 
RUN npx playwright install --with-deps

CMD ["bash"]
