name: CI Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:

  ### Build Backend (Node.js)
  build-backend:
    runs-on: ubuntu-latest

    # Set up postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test-user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

        # for npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          npm ci

      - name: Set up PostgreSQL
        working-directory: ./backend
        run: |
          echo "DB_DIALECT=postgres" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_USER=test-user" >> $GITHUB_ENV
          echo "DB_PASS=password" >> $GITHUB_ENV
          echo "DB_NAME=testdb" >> $GITHUB_ENV
          
        # starts server to check for basic compilation issues
      - name: Start Compiled Server & Kill 
        working-directory: ./backend
        run: |
          npm start & 
          SERVER_PID=$!
          sleep 5
          kill $SERVER_PID

        # zip step-- compress artifact (too large)
      - name: Zip Artifact Before Uploading
        working-directory: ./backend
        run: zip release.zip ./* -r

        # upload to be used later in the proceses
      - name: Upload Backend Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-build-artifact
          path: backend/release.zip

        
  ### Build Frontend (React.js)
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # for npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

        # install frontend dependencies from package.json
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: |
          npm ci

        # build frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm run build

        # zip step-- compress artifact
      - name: Zip Artifact Before Uploading
        working-directory: ./frontend
        run: zip release.zip ./* -r

        # upload to be used later in the process
      - name: Upload Frontend Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build-artifact
          path: frontend/release.zip

  #Installing playwright
  Playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: 
        npm install
        npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
  # Running Smoke Test    
    - name: Run smoke test
      run: npx playwright test smoke-test.js
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: smoke-report
        path: smoke-report/
        retention-days: 90








      
